// <auto-generated />
using System;
using EPM.PermissionMicroService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPM.PermissionMicroService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EPM.Model.DbModel.Menu", b =>
                {
                    b.Property<int>("ClusterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentMenuID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClusterID");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            ClusterID = 1,
                            CreateTime = new DateTime(2022, 1, 6, 15, 33, 41, 364, DateTimeKind.Local).AddTicks(5250),
                            CreateUser = "系统管理员",
                            ID = new Guid("ea22270d-fe74-4747-bca9-b97fd72033d5"),
                            IsDeleted = 0,
                            Name = "系统管理",
                            UpdateTime = new DateTime(2022, 1, 6, 15, 33, 41, 364, DateTimeKind.Local).AddTicks(5948),
                            UpdateUser = "系统管理员"
                        },
                        new
                        {
                            ClusterID = 2,
                            CreateTime = new DateTime(2022, 1, 6, 15, 33, 41, 364, DateTimeKind.Local).AddTicks(6569),
                            CreateUser = "系统管理员",
                            ID = new Guid("daa375e9-8761-4204-9560-5890146a9912"),
                            IsDeleted = 0,
                            Name = "用户管理",
                            ParentList = "ea22270d-fe74-4747-bca9-b97fd72033d5",
                            ParentMenuID = new Guid("ea22270d-fe74-4747-bca9-b97fd72033d5"),
                            UpdateTime = new DateTime(2022, 1, 6, 15, 33, 41, 364, DateTimeKind.Local).AddTicks(6576),
                            UpdateUser = "系统管理员"
                        },
                        new
                        {
                            ClusterID = 3,
                            CreateTime = new DateTime(2022, 1, 6, 15, 33, 41, 364, DateTimeKind.Local).AddTicks(7485),
                            CreateUser = "系统管理员",
                            ID = new Guid("3900326c-3deb-4f97-bce2-1dc0c4647d96"),
                            IsDeleted = 0,
                            Name = "角色管理",
                            ParentList = "ea22270d-fe74-4747-bca9-b97fd72033d5",
                            ParentMenuID = new Guid("ea22270d-fe74-4747-bca9-b97fd72033d5"),
                            UpdateTime = new DateTime(2022, 1, 6, 15, 33, 41, 364, DateTimeKind.Local).AddTicks(7486),
                            UpdateUser = "系统管理员"
                        },
                        new
                        {
                            ClusterID = 4,
                            CreateTime = new DateTime(2022, 1, 6, 15, 33, 41, 364, DateTimeKind.Local).AddTicks(7512),
                            CreateUser = "系统管理员",
                            ID = new Guid("0ec57811-7075-4817-8e16-54ad827a0557"),
                            IsDeleted = 0,
                            Name = "部门管理",
                            ParentList = "ea22270d-fe74-4747-bca9-b97fd72033d5",
                            ParentMenuID = new Guid("ea22270d-fe74-4747-bca9-b97fd72033d5"),
                            UpdateTime = new DateTime(2022, 1, 6, 15, 33, 41, 364, DateTimeKind.Local).AddTicks(7513),
                            UpdateUser = "系统管理员"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
